### ISSUE TITLE
Viewing documentation?

### ISSUE THREAD

**Issue by avahe-kellenberger** [clktmr/vim-gdscript3#4]
It would be great to have a way to view documentation using this plugin - Is there a way, or has anyone explored it?

**Comment by clktmr** [comment]
The plugin configures 'keywordprg' to open the official godot docs in
your browser via xdg-open.  You can try it by pressing 'K' in normal
mode if your cursor is placed on some token.  However since the
gdscript3 parser is still incomplete, it will often fallback to search
instead of opening the correct page directly.

Personally I would love to have the official documentation exported to
manpage or vimhelp format and bundled with this plugin.  This would
allow for reading it directly in vim, similar to godots builtin editor.

**Comment by avahe-kellenberger** [comment]
I saw recently that a language server for godot should be implemented (in 3.2 I believe), really looking forward to it. Thanks for your response
